Debug 1

GenericExecuteSynth \
"printf '%s' \"$DATA\" | /home/deck/.local/bin/piper-speechd \"$VOICE\" \"$RATE\""

GenericLanguage "en" "en_US" "utf-8"
GenericLanguage "en-us" "en_US" "utf-8"
GenericLanguage "cs" "cs_CZ" "utf-8"
GenericLanguage "es" "es_MX" "utf-8"
GenericLanguage "hu" "hu_HU" "utf-8"
GenericLanguage "ru" "ru_RU" "utf-8"

AddVoice "en-us" "FEMALE1" "en_US-amy-low"
AddVoice "en-us" "MALE1" "en_US-bryce-medium"
AddVoice "en-us" "FEMALE2" "en_US-hfc_female-medium"
AddVoice "en-us" "MALE2" "en_US-hfc_male-medium"
AddVoice "en-us" "FEMALE3" "en_US-kristin-medium"

AddVoice "en" "FEMALE1" "en_US-amy-low"
AddVoice "en" "MALE1" "en_US-bryce-medium"
AddVoice "en" "FEMALE2" "en_US-hfc_female-medium"
AddVoice "en" "MALE2" "en_US-hfc_male-medium"
AddVoice "en" "FEMALE3" "en_US-kristin-medium"

AddVoice "cs" "MALE1" "cs_CZ-jirka-medium"

AddVoice "es" "MALE1" "es_MX-claude-high"

AddVoice "hu" "FEMALE1" "hu_HU-berta-medium"
AddVoice "hu" "MALE1" "hu_HU-imre-medium"

AddVoice "ru" "MALE1" "ru_RU-ruslan-medium"

DefaultVoice "en_US-amy-low"
